services:
  boomerio:
    build:
      context: ./boomerio
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=boomerio.sqlite;
    networks:
      - boomerio-network
    restart: on-failure

networks:
  boomerio-network: