services:
  boomerio:
    build:
      context: ./boomerio
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BoomerShooterAPI;User ID=sa;Password=${SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - boomerio-network
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - boomerio-network

networks:
  boomerio-network:

volumes:
  sqlvolume: