name: Deploy 🚀

on:
  workflow_call:
    secrets:
      AZURE_PUBLISH_PROFILE:
        required: true

env:
  AZURE_WEB_APP_NAME: boomerio
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: dotnet publish boomerio/boomerio.csproj --configuration Release --runtime win-x86 --self-contained true --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
